language: node_js
node_js:
- '10'
cache: npm
install:
- npm install
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: kMmouqtBzsdOzAp7llunml0vd4EWJu7luWUZ1igBZzoHcD2XCSWLDei8uRUs7WTJeJW0UZTJ3f5omUtjLF0pgLEqh6LNpGq/hCWnNQ4dRFLGMlxH7S5sHEKyPWlspZkgPcA/GbvJk8Oh3hlYT5RJNOhFN/IzEpjNtWWaey0BoFBMdU2K1fmbDESBljX1/wdGJjDw28yOmr6lw4i5UdnSwugwjhhbkNSOI/NBeoaBX10mJZsCaOdcx39tbfTn0BDkmslCDj9tH0k1OL2bLah4GQDlGvHsYsHmvRA/DxfrP1q4p3DC7cDtX2ZIMoWjI3YZhwahB3ZC11D44w4Fq5T1ljBtph9tbFHsXFJ75Ik5PJN1Rotkwj4nDMK9+eB97RrEiUhI35Itpiw0xjhfaee4V5dfigokAzYQ7ilwh007Pgzk7fnj/+F0mLeNs8BlO6hoIaRv1NShdxi6JM/wXd6aoRN68H9GJfgc+fa9aThkHkH7M8pEU8m/z6FTKkyK02/T+LmxlTeESfidtbJkdu59dmMSThk6K7afJxnHysRXK9TQf/9g5bZgm7bhtb0KxIfJ24w0uF6XvTFbi995FkVQxDsxqhhueRqzdDTUOwqkMKwcmkO4LHRfAqQARx753lLj42zGvxnqizckp0cXC1hlNv6FX/ltHYDO69XglQN/kGo=
  app: workua-parser
